/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.iesb.pi.cadastrararea;

import br.iesb.pi.dados.CondominioDAO;
import br.iesb.pi.dados.DadosException;
import br.iesb.pi.entidades.Area;
import br.iesb.pi.entidades.Condominio;
import br.iesb.pi.pesquisararea.JFramePesquisarArea;
import javax.swing.JOptionPane;

/**
 *
 * @author Leilson
 */
public class JFrameCadastrarArea extends javax.swing.JFrame {

    /**
     * Creates new form JFrameCadastrarArea
     */
    public JFrameCadastrarArea() {
        initComponents();
        cbCondominio();
    }

    public void cbCondominio() {
        CondominioDAO dao = new CondominioDAO();

        try {
            for (Condominio c : dao.listar()) {
                cbCondominio.addItem(c);
            }
        } catch (DadosException ex) {
            JOptionPane.showMessageDialog(this, "Não foi possivel carregar Área. Deu ruim porque: " + ex, "Erro", JOptionPane.ERROR_MESSAGE);

        }
    }

    private Area area = new Area();

    public void editar(Area entidade) {
        String situacao;
        String ativo = "Ativo";
        String inativo = "Inativo";

        area = entidade;
        areatxt.setText(area.getArea());
        situacao = area.getSituacao();

        if (situacao.equals(ativo)) {
            Ativa.setSelected(true);
        } else if (situacao.equals(inativo)) {
            Inativa.setSelected(true);
        } else if (situacao.equals("")) {
            Ativa.setSelected(false);
            Inativa.setSelected(false);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbCondominio = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        areatxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Ativa = new javax.swing.JRadioButton();
        Inativa = new javax.swing.JRadioButton();
        Salvar = new javax.swing.JButton();
        Cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Cadastrar Áreas do Condomínio");

        jLabel2.setText("Condomínio");

        cbCondominio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Selecione um Condomínio--" }));

        jLabel3.setText("Área");

        jLabel4.setText("Situação");

        buttonGroup1.add(Ativa);
        Ativa.setText("Ativa");

        buttonGroup1.add(Inativa);
        Inativa.setText("Inativa");

        Salvar.setText("Salvar");
        Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvarActionPerformed(evt);
            }
        });

        Cancelar.setText("Cancelar");
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2)
                                .addComponent(cbCondominio, 0, 253, Short.MAX_VALUE)
                                .addComponent(areatxt))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Ativa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Salvar)
                                        .addGap(18, 18, 18)
                                        .addComponent(Cancelar))
                                    .addComponent(Inativa))))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbCondominio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(areatxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ativa)
                    .addComponent(Inativa))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Salvar)
                    .addComponent(Cancelar))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarActionPerformed

        Object a = "--Selecione um Condomínio--";
        Object b = cbCondominio.getSelectedItem();

        if (a.equals(b)) {
            JOptionPane.showMessageDialog(this, "Selecione um Condomínio", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        } else if (b.equals(null)) {
            JOptionPane.showMessageDialog(this, "Selecione um Condomínio", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        area.setCondominio((Condominio) b);
        area.setArea(areatxt.getText());
        if (Ativa.isSelected()) {
            area.setSituacao("Ativo");
        } else if (Inativa.isSelected()) {
            area.setSituacao("Inativo");
        } else {
            JOptionPane.showMessageDialog(this, "Situação não selecionado", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        AreaBO bo = new AreaBO();

        try {
            if (area.getId() == 0) {
                bo.inserir(area);
                JOptionPane.showMessageDialog(this, "Incluido com sucesso!!", "Informação", JOptionPane.INFORMATION_MESSAGE);
            } else {
                bo.alterar(area);
                JOptionPane.showMessageDialog(this, "Alterado com sucesso!!", "Informação", JOptionPane.INFORMATION_MESSAGE);
            }
            dispose();
            JFramePesquisarArea area = new JFramePesquisarArea();
            area.setVisible(true);
        } catch (AreaException ex) {
            if (ex.getCause() == null) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Aviso", JOptionPane.WARNING_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, ex.getCause().getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_SalvarActionPerformed

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        dispose();
        JFramePesquisarArea a = new JFramePesquisarArea();
        a.setVisible(true);
    }//GEN-LAST:event_CancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameCadastrarArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameCadastrarArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameCadastrarArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameCadastrarArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameCadastrarArea().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Ativa;
    private javax.swing.JButton Cancelar;
    private javax.swing.JRadioButton Inativa;
    private javax.swing.JButton Salvar;
    private javax.swing.JTextField areatxt;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<Object> cbCondominio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
